-- MySQL Script generated by MySQL Workbench
-- Sat May 14 22:15:30 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brands` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  UNIQUE INDEX `brands_name_unique` (`name` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 18
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 3
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `domains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domains` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 3
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `startDate` VARCHAR(255) NOT NULL,
  `endDate` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 58
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eventComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventComments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `eventId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `eventId` (`eventId` ASC),
  CONSTRAINT `eventcomments_ibfk_1`
  FOREIGN KEY (`eventId`)
  REFERENCES `events` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  AUTO_INCREMENT = 3
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `states` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `severity` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 5
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `models` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `brandId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  UNIQUE INDEX `models_name_unique` (`name` ASC),
  INDEX `brandId` (`brandId` ASC),
  CONSTRAINT `models_ibfk_1`
  FOREIGN KEY (`brandId`)
  REFERENCES `brands` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  AUTO_INCREMENT = 21
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(255) NOT NULL,
  `isInStock` TINYINT(1) NOT NULL DEFAULT '1',
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `stateId` INT(11) NULL DEFAULT NULL,
  `modelId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `stateId` (`stateId` ASC),
  INDEX `modelId` (`modelId` ASC),
  CONSTRAINT `items_ibfk_1`
  FOREIGN KEY (`stateId`)
  REFERENCES `states` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `items_ibfk_2`
  FOREIGN KEY (`modelId`)
  REFERENCES `models` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  AUTO_INCREMENT = 81
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `itemComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itemComments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `itemId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `itemId` (`itemId` ASC),
  CONSTRAINT `itemcomments_ibfk_1`
  FOREIGN KEY (`itemId`)
  REFERENCES `items` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  AUTO_INCREMENT = 6
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `linkedItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linkedItems` (
  `itemId` INT(11) NOT NULL DEFAULT '0',
  `linkedItemId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`itemId`, `linkedItemId`),
  INDEX `linkedItemId` (`linkedItemId` ASC),
  CONSTRAINT `linkeditems_ibfk_1`
  FOREIGN KEY (`itemId`)
  REFERENCES `items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `linkeditems_ibfk_2`
  FOREIGN KEY (`linkedItemId`)
  REFERENCES `items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `subCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subCategories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `categoryId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoryId` (`categoryId` ASC),
  CONSTRAINT `subcategories_ibfk_1`
  FOREIGN KEY (`categoryId`)
  REFERENCES `categories` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  AUTO_INCREMENT = 5
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `modelCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelCategory` (
  `modelId` INT(11) NOT NULL DEFAULT '0',
  `subCategoryId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`modelId`, `subCategoryId`),
  INDEX `subCategoryId` (`subCategoryId` ASC),
  CONSTRAINT `modelcategory_ibfk_1`
  FOREIGN KEY (`modelId`)
  REFERENCES `models` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `modelcategory_ibfk_2`
  FOREIGN KEY (`subCategoryId`)
  REFERENCES `subCategories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `modelDomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelDomain` (
  `modelId` INT(11) NOT NULL DEFAULT '0',
  `domainId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`modelId`, `domainId`),
  INDEX `domainId` (`domainId` ASC),
  CONSTRAINT `modeldomain_ibfk_1`
  FOREIGN KEY (`modelId`)
  REFERENCES `models` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `modeldomain_ibfk_2`
  FOREIGN KEY (`domainId`)
  REFERENCES `domains` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `reservedItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservedItems` (
  `itemId` INT(11) NOT NULL DEFAULT '0',
  `eventId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`itemId`, `eventId`),
  INDEX `eventId` (`eventId` ASC),
  CONSTRAINT `reserveditems_ibfk_1`
  FOREIGN KEY (`itemId`)
  REFERENCES `items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `reserveditems_ibfk_2`
  FOREIGN KEY (`eventId`)
  REFERENCES `events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `login` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `enabled` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login` (`login` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `users_login_unique` (`login` ASC),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 3
  DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
