-- MySQL Script generated by MySQL Workbench
-- Sat May 14 22:15:30 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lrds
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lrds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lrds` DEFAULT CHARACTER SET latin1 ;
USE `lrds` ;

-- -----------------------------------------------------
-- Table `lrds`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`brands` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  UNIQUE INDEX `brands_name_unique` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`domains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`domains` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `startDate` VARCHAR(255) NOT NULL,
  `endDate` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`eventComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`eventComments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `eventId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `eventId` (`eventId` ASC),
  CONSTRAINT `eventcomments_ibfk_1`
    FOREIGN KEY (`eventId`)
    REFERENCES `lrds`.`events` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`states` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `severity` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`models` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `brandId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  UNIQUE INDEX `models_name_unique` (`name` ASC),
  INDEX `brandId` (`brandId` ASC),
  CONSTRAINT `models_ibfk_1`
    FOREIGN KEY (`brandId`)
    REFERENCES `lrds`.`brands` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(255) NOT NULL,
  `isInStock` TINYINT(1) NOT NULL DEFAULT '1',
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `stateId` INT(11) NULL DEFAULT NULL,
  `modelId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `stateId` (`stateId` ASC),
  INDEX `modelId` (`modelId` ASC),
  CONSTRAINT `items_ibfk_1`
    FOREIGN KEY (`stateId`)
    REFERENCES `lrds`.`states` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `items_ibfk_2`
    FOREIGN KEY (`modelId`)
    REFERENCES `lrds`.`models` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`itemComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`itemComments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `itemId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `itemId` (`itemId` ASC),
  CONSTRAINT `itemcomments_ibfk_1`
    FOREIGN KEY (`itemId`)
    REFERENCES `lrds`.`items` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`linkedItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`linkedItems` (
  `itemId` INT(11) NOT NULL DEFAULT '0',
  `linkedItemId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`itemId`, `linkedItemId`),
  INDEX `linkedItemId` (`linkedItemId` ASC),
  CONSTRAINT `linkeditems_ibfk_1`
    FOREIGN KEY (`itemId`)
    REFERENCES `lrds`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `linkeditems_ibfk_2`
    FOREIGN KEY (`linkedItemId`)
    REFERENCES `lrds`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`subCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`subCategories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `categoryId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoryId` (`categoryId` ASC),
  CONSTRAINT `subcategories_ibfk_1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `lrds`.`categories` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`modelCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`modelCategory` (
  `modelId` INT(11) NOT NULL DEFAULT '0',
  `subCategoryId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`modelId`, `subCategoryId`),
  INDEX `subCategoryId` (`subCategoryId` ASC),
  CONSTRAINT `modelcategory_ibfk_1`
    FOREIGN KEY (`modelId`)
    REFERENCES `lrds`.`models` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `modelcategory_ibfk_2`
    FOREIGN KEY (`subCategoryId`)
    REFERENCES `lrds`.`subCategories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`modelDomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`modelDomain` (
  `modelId` INT(11) NOT NULL DEFAULT '0',
  `domainId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`modelId`, `domainId`),
  INDEX `domainId` (`domainId` ASC),
  CONSTRAINT `modeldomain_ibfk_1`
    FOREIGN KEY (`modelId`)
    REFERENCES `lrds`.`models` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `modeldomain_ibfk_2`
    FOREIGN KEY (`domainId`)
    REFERENCES `lrds`.`domains` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`reservedItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`reservedItems` (
  `itemId` INT(11) NOT NULL DEFAULT '0',
  `eventId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`itemId`, `eventId`),
  INDEX `eventId` (`eventId` ASC),
  CONSTRAINT `reserveditems_ibfk_1`
    FOREIGN KEY (`itemId`)
    REFERENCES `lrds`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `reserveditems_ibfk_2`
    FOREIGN KEY (`eventId`)
    REFERENCES `lrds`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lrds`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrds`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `login` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `enabled` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login` (`login` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `users_login_unique` (`login` ASC),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

USE `lrds` ;

-- -----------------------------------------------------
-- procedure add_brand
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_brand`(
  IN name VARCHAR(255),
  IN description VARCHAR(255)
)
BEGIN

    INSERT INTO brands (name, description) VALUES(name, description);

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_category
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_category`(
  IN name VARCHAR(255),
  IN description VARCHAR(255)
)
BEGIN

    INSERT INTO categories (name, description) VALUES(name, description);

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_domain
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_domain`(
  IN name VARCHAR(255),
  IN description VARCHAR(255)
)
BEGIN

    INSERT INTO domains (name, description) VALUES(name, description);

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_event
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_event`(
  IN eventName VARCHAR(255),
  IN description TEXT,
  IN startDate DATETIME,
  IN endDate DATETIME
)
BEGIN

    INSERT INTO events (name, description, startDate, endDate, createdAt, updatedAt) VALUES(eventName, description, startDate, endDate, now(), now());

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_event_comment
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_event_comment`(
  IN eventName VARCHAR(255),
  IN itemReference VARCHAR(255)
)
BEGIN

    SET @eventId := (SELECT id FROM events WHERE name = eventName);

    INSERT INTO eventComments (text, eventId, createdAt, updatedAt) VALUES(text, @eventId, now(), now());

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_item
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_item`(
  IN reference VARCHAR(255),
  IN isInStock BOOLEAN,
  IN modelName VARCHAR(255),
  IN stateName VARCHAR(255)
)
BEGIN

    SET @modelId := (SELECT id FROM models WHERE name = modelName);
    SET @stateId := (SELECT id FROM states WHERE name = stateName);

    INSERT INTO items (reference, isInStock, modelId, stateId, createdAt, updatedAt) VALUES(reference, isInStock, @modelId, @stateId, now(), now());

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_item_comment
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_item_comment`(
  IN text VARCHAR(255),
  IN itemReference VARCHAR(255)
)
BEGIN

    SET @itemId := (SELECT id FROM items WHERE reference = itemReference);

    INSERT INTO itemComments (text, itemId, createdAt, updatedAt) VALUES(text, @itemId, now(), now());

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_model
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_model`(
  IN modelName VARCHAR(255),
  IN description VARCHAR(255),
  IN brandName VARCHAR(255)
)
BEGIN

    SET @brandId := (SELECT id FROM brands WHERE name = brandName);

    INSERT INTO models (name, description, brandId) VALUES(modelName, description, @brandId);

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_state
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_state`(
  IN name VARCHAR(255),
  IN severity INT
)
BEGIN

    INSERT INTO states (name, severity) VALUES(name, severity);

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_subCategory
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `add_subCategory`(
  IN subCategoryName VARCHAR(255),
  IN description VARCHAR(255),
  IN categoryName VARCHAR(255)
)
BEGIN

    SET @categoryId := (SELECT id FROM categories WHERE name = categoryName);
    INSERT INTO subCategories (name, description, categoryId) VALUES(subCategoryName, description, @categoryId);

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure bind_item_to_event
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `bind_item_to_event`(
  IN eventName VARCHAR(255),
  IN itemName VARCHAR(255)
)
BEGIN

    SET @eventId := (SELECT id FROM events WHERE name = eventName);
    SET @itemId := (SELECT Id FROM items WHERE reference = itemName);
    
    INSERT INTO reservedItems (eventId, itemId) VALUES(@eventId, @itemId);

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure bind_model_to_domain
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `bind_model_to_domain`(
  IN modelName VARCHAR(255),
  IN domainName VARCHAR(255)
)
BEGIN

    SET @modelId := (SELECT id FROM models WHERE name = modelName);
    SET @domainId := (SELECT id FROM domains WHERE name = domainName);
    INSERT INTO modelDomain (modelId, domainId) VALUES(@modelId, @domainId);

  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure bind_model_to_subCategory
-- -----------------------------------------------------

DELIMITER $$
USE `lrds`$$
CREATE DEFINER=`greec`@`localhost` PROCEDURE `bind_model_to_subCategory`(
  IN modelName VARCHAR(255),
  IN subCategoryName VARCHAR(255)
)
BEGIN

    SET @modelId := (SELECT id FROM models WHERE name = modelName);
    SET @subCategoryId := (SELECT Id FROM subCategories WHERE name = subCategoryName);
    INSERT INTO modelCategory (modelId, subCategoryId) VALUES(@modelId, @subCategoryId);

  END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
